import '../Models/processados_animal.dart';
import '../Models/processados_vegetal.dart';

class ProcessadosRepository {
  static var listProcessadosVegetais = [
    'Açúcar mascavo',
    'Amido de milho',
    'Artesanato (geral)',
    'Artesanato com partes vegetais (semente, casca, folhas, flores)',
    'Artesanato em barro ou argila',
    'Artesanato em fibra',
    'Artesanato em madeira',
    'Artesanato têxtil',
    'Banana chips',
    'Bebida láctea',
    'Borracha ou látex nativo',
    'Borracha ou látex plantado',
    'Buriti – polpa',
    'Cachaça',
    'Café torrado e moído',
    'Chá de ervas',
    'Conservas',
    'Doce de leite',
    'Doce, geleia ou compota de frutas',
    'Farinha de babaçu',
    'Farinha de banana',
    'Farinha de castanha-do-brasil',
    'Farinha de mandioca tipo amarela',
    'Farinha de mandioca tipo branca',
    'Farinha de milho',
    'Fitoterápicos (ervas medicinais)',
    'Frutas desidratadas',
    'Frutas e legumes descascados e embalados',
    'Fubá de milho',
    'Iogurte',
    'Mandioca chips',
    'Mandioca descascada',
    'Melado',
    'Óleo de andiroba',
    'Óleo de babaçu',
    'Óleo de buriti',
    'Óleo de castanha-do-brasil ou castanha-do-pará',
    'Óleo'
  ];

  static var listProcessadosAnimal = [
    'Carne bovina',
    'Carne de caprino',
    'Carne de coelho',
    'Carne de frango caipira',
    'Carne de frango comum',
    'Carne de ovino',
    'Queijo prato',
    'Carne suína',
    'Charque bovino',
    'Couro',
    'Embutido apresuntado',
    'Embutido salame',
    'Embutidos artesanais',
    'Frango - Coxa e sobrecoxa',
    'Frango - Peito com osso',
    'Frango - Peito desossado (sem osso)',
    'Frango – retalho',
    'Geleia real',
    'Gordura animal ou banha',
    'Leite bovino em pó',
    'Leite bovino integral pasteurizado (saquinho)',
    'Leite bovino integral UHT (caixinha)',
    'Leite condensado',
    'Manteiga',
    'Mel de abelha europeia (Apis)',
    'Mel de abelha nativa',
    'Ovos de codorna',
    'Ovos de galinha – branco',
    'Ovos de galinha caipira',
    'Ovos de galinha – vermelho',
    'Peixe – Outras espécies',
    'Peixe – Pintado',
    'Peixe – Tambacu',
    'Peixe –Tambaqui',
    'Peixe –Tambatinga',
    'Peixe –Tilápia',
    'Própolis',
    'Queijo coalho',
    'Queijo meia cura',
    'Queijo minas frescal',
    'Queijo muçarela',
    'Queijo parmesão',
    'Queijo provolone',
    'Queijo ricota',
    'Requeijão'
  ];
}
