class VegetaisRepository {
  static var listVegetais = [
    "Abacate (unidade)",
    "Abacaxi havaí (unidade)",
    "Abacaxi pérola (unidade)",
    "Abóbora cabotiã (unidade)",
    "Abóbora moranga (unidade)",
    "Abóbora paulista (unidade)",
    "Abobrinha menina brasileira (unidade)",
    "Abobrinha verde (unidade)",
    "Açaí – fruta (kg)",
    "Açaí – palmito (kg)",
    "Acelga (maço)",
    "Acerola (unidade)",
    "Agrião (unidade)",
    "Alface americana (maço)",
    "Alface crespa (maço)",
    "Alface lisa (maço)",
    "Alface romana (maço)",
    "Alho branco (kg)",
    "Alho roxo (kg)",
    "Almeirão (maço)",
    "Amendoim (kg)",
    "Araruta (kg)",
    "Araticum (unidade)",
    "Arroz (kg)",
    "Atemoia (unidade)",
    "Babaçu (mesocarpo e amêndoa) (kg)",
    "Banana da terra (unidade)",
    "Banana maçã (unidade)",
    "Banana nanica (unidade)",
    "Banana ouro (unidade)",
    "Banana pacovan (unidade)",
    "Banana prata (unidade)",
    "Batata doce (kg)",
    "Batata lisa ou inglesa (kg)",
    "Berinjela (unidade)",
    "Beterraba (unidade)",
    "Biribá (unidade)",
    "Brócolis (unidade)",
    "Buriti (unidade)",
    "Cacau (kg)",
    "Café arábica (kg)",
    "Café canéfora (kg)",
    "Caju – castanha (kg)",
    "Caju – fruta (unidade)",
    "Cana-de-açúcar (tonelada)",
    "Cará (unidade)",
    "Castanha-do-brasil ou castanha-do-pará (kg)",
    "Caxi (unidade)",
    "Cebola branca (unidade)",
    "Cebola roxa (unidade)",
    "Cebolinha verde (maço)",
    "Cenoura (kg)",
    "Chicória (maço)",
    "Chuchu (unidade)",
    "Coco verde (unidade)",
    "Coentro (maço)",
    "Couve comum (maço)",
    "Couve manteiga (maço)",
    "Couve-flor (unidade)",
    "Cumbaru ou baru (castanha) (kg)",
    "Cupuaçu (kg)",
    "Ervilha (kg)",
    "Espinafre (maço)",
    "Fava (kg)",
    "Feijão carioquinha (kg)",
    "Feijão caupi (kg)",
    "Feijão preto (kg)",
    "Figo (unidade)",
    "Flores (dúzia)",
    "Framboesa (unidade)",
    "Gergelim (kg)",
    "Girassol (kg)",
    "Goiaba (unidade)",
    "Grão-de-bico (kg)",
    "Graviola (unidade)",
    "Guaraná (semente) (kg)",
    "Hortelã (maço)",
    "Inhame (kg)",
    "Jabuticaba (unidade)",
    "Jaca (unidade)",
    "Jambo (unidade)",
    "Jenipapo (unidade)",
    "Jiló (unidade)",
    "Laranja bahia ou baía (unidade)",
    "Laranja lima (unidade)",
    "Laranja pera (unidade)",
    "Leite (unidade)",
    "Lentilha (kg)",
    "Lima (unidade)",
    "Limão galego (unidade)",
    "Limão rosa (unidade)",
    "Limão taiti (unidade)",
    "Maçã fuji (unidade)",
    "Maçã gala (unidade)",
    "Maçã nacional (unidade)",
    "Macaúba ou bocaiúva (unidade)",
    "Mamão formosa (unidade)",
    "Mamão papaya (unidade)",
    "Mamona (unidade)",
    "Mandioca, aipim ou macaxeira (kg)",
    "Manga (unidade)",
    "Mangaba (unidade)",
    "Mangarito (unidade)",
    "Manjericão (maço)",
    "Maracujá (unidade)",
    "Maxixe (unidade)",
    "Melancia (unidade)",
    "Melão amarelo (unidade)",
    "Melão caipira (unidade)",
    "Milho (grão seco) (kg)",
    "Milho de pipoca (kg)",
    "Milho verde (unidade)",
    "Morango (unidade)",
    "Mostarda (maço)",
    "Murici (unidade)",
    "Palmito juçara (kg)",
    "Pepino aodai ou comum (unidade)",
    "Pepino caipira (unidade)",
    "Pepino japonês (unidade)",
    "Pequi ou piqui (unidade)",
    "Pimenta de cheiro (kg)",
    "Pimenta-do-reino ou pimenta preta (kg)",
    "Pimentão (unidade)",
    "Pitaia ou pitaya (unidade)",
    "Pitanga (unidade)",
    "Pupunha – fruta (unidade)",
    "Pupunha – palmito (kg)",
    "Quiabo (unidade)",
    "Rabanete (unidade)",
    "Repolho branco (unidade)",
    "Repolho roxo (unidade)",
    "Romã (unidade)",
    "Rúcula (maço)",
    "Salsa (maço)",
    "Semente nativa (kg)",
    "Seringueira (unidade)",
    "Silvicultura – madeira (unidade)",
    "Soja (unidade familiar) (kg)",
    "Taioba (unidade)",
    "Tangerina morgot, morcote ou murcote (unidade)",
    "Tangerina ponkan, poncan ou poncã (unidade)",
    "Tomate caqui (unidade)",
    "Tomate cereja (unidade)",
    "Tomate salada (unidade)",
    "Trigo (kg)",
    "Urucum (unidade)",
    "Uva niágara (cachos)",
    "Uva rubi (cachos)",
    "Vagem (kg)"
  ];
}
